import JSZip from 'jszip';
import { Waypoint, MissionParameters } from '@/types/mission';

export function exportToKMZ(waypoints: Waypoint[], parameters: MissionParameters): Promise<Blob> {
  return new Promise((resolve, reject) => {
    try {
      const zip = new JSZip();
      
      // Crear el contenido KML
      const kmlContent = generateKML(waypoints, parameters);
      
      // Añadir el archivo KML al ZIP
      zip.file('mission.kml', kmlContent);
      
      // Generar el archivo KMZ (ZIP)
      zip.generateAsync({ type: 'blob' })
        .then(blob => resolve(blob))
        .catch(error => reject(error));
    } catch (error) {
      reject(error);
    }
  });
}

function generateKML(waypoints: Waypoint[], parameters: MissionParameters): string {
  const centerCoords = parameters.center;
  const poiCoords = centerCoords;
  
  // Calcular altitudes relativas al suelo (usar altitud del terreno como base)
  const takeoffAltitude = 0; // Base del terreno
  
  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2">
  <Document>
    <name>Viizor UAV Mission</name>
    <description>Mission generated by Viizor - UAV Mission Planner</description>
    
    <!-- Estilos -->
    <Style id="waypointStyle">
      <IconStyle>
        <color>ff00ff00</color>
        <scale>0.8</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    
    <Style id="photoWaypointStyle">
      <IconStyle>
        <color>ff7700ff</color>
        <scale>1.0</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/camera.png</href>
        </Icon>
      </IconStyle>
    </Style>
    
    <Style id="centerStyle">
      <IconStyle>
        <color>ffff0000</color>
        <scale>1.2</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/target.png</href>
        </Icon>
      </IconStyle>
    </Style>
    
    <Style id="orbitLineStyle">
      <LineStyle>
        <color>7f0000ff</color>
        <width>3</width>
      </LineStyle>
    </Style>
    
    <!-- Centro de Órbita -->`;

  if (centerCoords) {
    kml += `
    <Placemark>
      <name>Centro de Órbita</name>
      <description>Centro de la órbita de la misión</description>
      <styleUrl>#centerStyle</styleUrl>
      <Point>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>${centerCoords.lng},${centerCoords.lat},${parameters.initialAltitude - takeoffAltitude}</coordinates>
      </Point>
    </Placemark>`;
  }

  // Point of Interest
  if (poiCoords) {
    kml += `
    <Placemark>
      <name>Point of Interest</name>
      <description>Objetivo de las fotografías</description>
      <styleUrl>#centerStyle</styleUrl>
      <Point>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>${poiCoords.lng},${poiCoords.lat},${(parameters.targetAltitude || 0) - takeoffAltitude}</coordinates>
      </Point>
    </Placemark>`;
  }

  // Waypoints
  waypoints.forEach((waypoint) => {
    const style = waypoint.takePhoto ? 'photoWaypointStyle' : 'waypointStyle';
    const name = waypoint.takePhoto ? 'Foto' : 'Waypoint';
    
    kml += `
    <Placemark>
      <name>${name} ${waypoint.id}</name>
      <description>
        Altitud: ${waypoint.altitude.toFixed(1)}m&lt;br/&gt;
        Heading: ${waypoint.heading.toFixed(1)}°&lt;br/&gt;
        Velocidad: ${waypoint.speed.toFixed(1)}m/s&lt;br/&gt;
        ${waypoint.takePhoto ? 'Punto de fotografía' : 'Waypoint de navegación'}
      </description>
      <styleUrl>#${style}</styleUrl>
      <Point>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>${waypoint.longitude},${waypoint.latitude},${waypoint.altitude - takeoffAltitude}</coordinates>
      </Point>
    </Placemark>`;
  });

  // Línea de la órbita
  if (waypoints.length > 1) {
    kml += `
    <Placemark>
      <name>Ruta de Vuelo</name>
      <description>Trayectoria completa de la misión</description>
      <styleUrl>#orbitLineStyle</styleUrl>
      <LineString>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>`;
    
    waypoints.forEach((waypoint) => {
      kml += `${waypoint.longitude},${waypoint.latitude},${waypoint.altitude - takeoffAltitude} `;
    });
    
    kml += `</coordinates>
      </LineString>
    </Placemark>`;
  }

  kml += `
  </Document>
</kml>`;

  return kml;
}