// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdqyftcclamrldvpvctr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkcXlmdGNjbGFtcmxkdnB2Y3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTc3NDEsImV4cCI6MjA2ODI3Mzc0MX0.RZqNnLsQ2NDKEb7gfws_UvGVMZS0vOhhudx5iWnvRFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});